/**
 * JokeAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package hu.bme.aut.jokes.data.network.model

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 *
 * @param category
 * @param type
 * @param flags
 * @param id
 * @param safe
 * @param lang
 * @param error
 * @param setup
 * @param delivery
 * @param joke
 */
@JsonClass(generateAdapter = true)
data class JokeDto(
    @Json(name = "category")
    val category: kotlin.String,
    @Json(name = "type")
    val type: JokeDto.Type,
    @Json(name = "flags")
    val flags: FlagsDto,
    @Json(name = "id")
    val id: kotlin.Long,
    @Json(name = "safe")
    val safe: kotlin.Boolean,
    @Json(name = "lang")
    val lang: kotlin.String,
    @Json(name = "error")
    val error: kotlin.Boolean? = null,
    @Json(name = "setup")
    val setup: kotlin.String? = null,
    @Json(name = "delivery")
    val delivery: kotlin.String? = null,
    @Json(name = "joke")
    val joke: kotlin.String? = null
) {

    /**
     *
     * Values: SINGLE,TWOPART
     */

    enum class Type(val value: kotlin.String) {
        @Json(name = "single")
        SINGLE("single"),
        @Json(name = "twopart")
        TWOPART("twopart");
    }
}

